#!/usr/bin/zsh

aws(){
	local verb="$1"
	local mod="$2"

	case "$verb" in
	ssh)
		if [ -n "$2" ]; then
			# Use provided profile
			profile="dev"
			[ -z "$3" ] || profile="$3"

			instance="$2"
			[ "${instance:0:2}" = "i-" ] || instance="i-$2"

			#snag the public dns
			pubdns=$(command aws ec2 describe-instances --instance-ids "$instance" --profile "$profile" 2>&1 | grep PublicDnsName | head -n 1 | cut -d "\"" -f 4)
		
			[ -z "$pubdns" ] || ssh -A -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "$pubdns"
		fi
	;;
	*)
		command aws "$@"
	;;
	esac
}

# vim: filetype=zsh noexpandtab
